### ISSUE TITLE
Demo File

### ISSUE THREAD

**Issue by BitFis** [uhlik/bpy#16]
Hello

Thank you for your great plugin. I try to get it to work for blender 2.8. It works all well, but it seems like the ply files are not supported. do you have anywhere an working ply file as an example?
This would help so much

Thank you very much

Regards

**Comment by BitFis** [comment]
I tryed to import those from here: https://people.sc.fsu.edu/~jburkardt/data/ply/ply.html

**Comment by uhlik** [comment]
hi, you seems to find a bug in ply reader, they define vertices as float32/float64 instead of float/double, i will fix that, but those ply file won't show you anything much interesting because they are polygonal ply files instead of point cloud files, that examples has no normals and colors on vertices, you will see just sparse gray points.. here is an example of point cloud ply: https://github.com/potree/PotreeConverter/blob/develop/test/resources/ripple_bin.ply
generally you get point clouds from laser scanning, photogrammetry etc..

**Comment by uhlik** [comment]
fixed, those files you linked now can be loaded
