### ISSUE TITLE
Convert all the imported point clouds to isospheres with vertex colors using script

### ISSUE THREAD

**Issue by thingsontopofotherthings** [uhlik/bpy#51]
Hi there. I was wondering, as my title says if you know how to convert all the imported point clouds to isospheres with vertex colors using script. I want the converted objects to inherit the same keyframes for animation.
I'm very new to blender and python so any help would be very appreaciated. 

Best wishes. 
T

**Comment by uhlik** [comment]
hi, animation is not supported because all mesh instances will be merged into one single mesh. and one more note, blender does not handle many separate objects well, so i think it will freeze after several hundreds of instances (at least i experienced it in the past). maybe in the future with geometry nodes it will be possible in some form, but not now.
