### ISSUE TITLE
Import Agisoft Cameras in Blender 2.93.4

### ISSUE THREAD

**Issue by solosails** [uhlik/bpy#54]
Hi there, 

Tried to install your import Agisoft cameras xml addon in Blender 2.93.4m it will enable, but I cannot see it listed in the scene menu? 

Is it not compatible above 2.80?

Many thanks.

**Comment by uhlik** [comment]
are you sure? works for me in 2.93.4. it is located in Properties area (aka buttons) > Scene Properties tab > Import PhotoScan Cameras subpanel

**Comment by PLAN8VR** [comment]
Hey, how’s it going?Recently, I’ve been experimenting with editing pointclouds prior to use in Gaussian splatting software, including procedurally graduating the density based on scalar proximity values (which I just noticed you can create in your plugin) I have been using Cloudcompare to do this up to now. Anyway, my question is, is it possible to “paint” (weight paint) scalars in your plugin? I ask because there is a discussion about allowing Brush Gaussian splatting software be able to read scalars. If this were the case, then the ability to use your plugin inside blender to weight paint scalars could be very useful indeed. These painted scalars can then instruct the radiance field algorithms to concentrate training on a specific area etc. Maybe this is possible already? If not, could you add it?Also, I use the photogrammetry importer plugin by sbcv, there appears to be big clashes between the two plugins, to do with the python libraries, to the point I’ve actually had to uninstall your plugin as it breaks the other and currently the ability to import/export colmap format with the other plugin is priority. Is there any way the two could play nicely together?All the best, Andrew. On 5 Oct 2021, at 18:32, uhlik ***@***.***> wrote:﻿
are you sure? works for me in 2.93.4. it is located in Properties area (aka buttons) > Scene Properties tab > Import PhotoScan Cameras subpanel

**Comment by uhlik** [comment]
since i have no idea what pcv version you are talking about, i assume the latest, superhive one, because i don't develop nor support the one in this repo. you can do a lot of things with scalars in pcv, "brushing" as you would imagine so far not. point clouds have no surface, making brush like tool is very tricky. but i can add it to todo, we'll see. then the "clashes", not sure what you mean. pcv is extension, all libraries are bundled, as per blender directions. sbcv's is legacy addon, no idea how it installs libraries, but anything else then bundling wheels to extension is not officially supported by blender, it was always a hack.

**Comment by PLAN8VR** [comment]
Hi, yeah sorry latest version (just found an old email thread from a while back to use to email you)So, yeah, if you could have a think about if it might be possible to paint/brush on scalar fields that would be great. Re clashes, well, don’t worry about it, I don’t know exactly what happened, but I clicked the tool in your conflicts settings and it made some changes to some common libraries between the two plugins. TBH I have no idea what happened, but they both use 3 or 4 similar libraries. Don’t worry about it. But the brushing system could be good. I sort of got half way there, I think I realised that you needed faces to assign weight/vertex paints, so imported a rough mesh of the pointcloud, painted that and I’m currently working out how to transfer this weights to scalars in the pointcloud. Looks like you can do it, but I haven’t figured it out yet. Anyway, thanks for your response. I’ll update you if “Brush” decides to enable scalar utilities, if so I will be pushing your addon as a tool to create those. I’ll probably do that anyway as it is such a useful tool just for creating mesh distance scalars etc. If you haven’t heard of it, brush repo is here https://github.com/ArthurBrussee/brushCheers, Andrew. On 12 Nov 2025, at 12:43, uhlik ***@***.***> wrote:﻿uhlik left a comment (uhlik/bpy#54)
since i have no idea what pcv version you are talking about, i assume the latest, superhive one, because i don't develop nor support the one in this repo. you can do a lot of things with scalars in pcv, "brushing" as you would imagine so far not. point clouds have no surface, making brush like tool is very tricky. but i can add it to todo, we'll see. then the "clashes", not sure what you mean. pcv is extension, all libraries are bundled, as per blender directions. sbcv's is legacy addon, no idea how it installs libraries, but anything else then bundling wheels to extension is not officially supported by blender, it was always a hack.

**Comment by uhlik** [comment]
the tool is meant to do cleanup of all what pcv before being extension did, as byproduct it will also cleanup other addons installed libraries if they used the same destination, i.e. user site-packages directory. i mention that in instructions.. and if somehow pcv library and other addon library is the same, first one used will be loaded and used by python until blender quits, this can lead to api incompatibilities between same library and its different versions. that's one thing blender does not have really resolved yet.. pcv does not load any library until some user action requires it.

with the painting, main issue is, points are infinitesimal dots in space that is "more hole" then points, so brush stroke must be positioned in space so it affects points you might want to and not those behind etc. that's not easy task to be actually usable from user side. but it seems like interesting problem to solve.. anyway, thanks for suggestion.

please, next time contact me on superhive, that's better place for this
cheers

**Comment by PLAN8VR** [comment]
Hi. Sorry, I was just using email, didnt realise it was publishing github issues!
