### ISSUE TITLE
Normals won't render ...

### ISSUE THREAD

**Issue by ricemcm** [uhlik/bpy#55]
If I open a .PLY file in Blender, with normals showing, how can I render (to PNG) both the point cloud AND/OR the surface normals using Point Cloud Visualizer?

Thanks,
Justin

**Comment by fairwelljack** [comment]
> hi, normals rendering is not supported, but can be done. will be in next version.

Hi, is PCV2 support render normals with customized mesh in geometry notes? thank you!

**Comment by uhlik** [comment]
hi, pcv 2.0 renders normals with it's own opengl rendering on screen or to image. it have nothing to do with geometry nodes. i don't understand do you mean with it. if you are asking if conversion to geometry nodes keeps normals, then yes, point normals are added as custom vector attribute on result vertices (not regular normal attribute because blender will recalculate them to something else), together with colors and all scalar values from original points, then you can use any of this in geometry nodes. if you have any other questions, please write me on blendermarket.
