### ISSUE TITLE
Viewer in VR Scene

### ISSUE THREAD

**Issue by JunhuaLiu0** [uhlik/bpy#67]
Hi, I am planning to play point cloud animation in a VR headset. This add-on is really fit for my idea. But I have some problems when using it.

I use VR Scene Inspection to display the point cloud. I could view the point cloud on my PC. But in VR, it displays the object I attached the point cloud to(or empty object?). It seems that the point cloud can be only viewed in blender GUI, but not generate a new point cloud object.

If I convert the point cloud into particle, or enter edit. I could see the point cloud but it does not have color. It also takes much time to convert.

Do you have any idea to make it visualize in VR Scene? 

Thank you very much. Although it's not very polite, I really need this.

**Comment by uhlik** [comment]
hi, from reading blender docs i think vr viewport is something totally different from regular viewport in blender, and since pcv draws itself to `bpy.types.SpaceView3D` you don't see anything in vr. types related to vr are beginning with `Xr` prefix in python api and there is no view, so i guess vr viewport is not exposed to python at all, so i can't help. what you could do is convert your points to geometry nodes with color attribute and somehow get vr viewport to draw vertex colors on generated meshes (regular viewport can do that), but since i don't have any vr hardware i can't confirm that. and also this is feature of pcv 2.0 that is paid.
