### ISSUE TITLE
Is this a scaling problem?

### ISSUE THREAD

**Issue by MariaMel98** [uhlik/bpy#73]
Hello again. The ply file I'm trying to visualize is a point cloud from a forest scene as seen below using cloudcompare software. When I import it to blender using point_cloud_visualizer all I see is a very thick line of points as you can see. I wanted to ask if this is a scaling problem and can be fixed with scale changing (I have tried a lot of different scaling changes but with no success)  Thank you in advance!
![Στιγμιότυπο οθόνης (83)](https://user-images.githubusercontent.com/105556892/186360316-dca8d829-b623-4ffd-853d-190276823eda.png)
![Στιγμιότυπο οθόνης (84)](https://user-images.githubusercontent.com/105556892/186360349-1fb3fe4a-0071-4058-a7f6-eafb3e35fa08.png)

**Comment by uhlik** [comment]
yes, it looks like that. can't be sure from screenshot, but coordinates from cc are pretty wild.

this old pcv version (0.9) from this repository is not able to correct that. it loads raw points always as single precision floats (because of blender gpu api need that). to correct that, points have to be moved and/or scaled to fit in precision range, if it is stored as doubles in file (there's no help if not) and after that turned to floats for display. pcv 2.0 can do that. even re-apply on export if wanted.

you can apply transformation in cc (if i remember it asks you on import or export if it detects out of range problems) and use ply exported from cc in old pcv. that should fix it.

and if you have no colors on points, old pcv cannot read scalars, only colors. scalars are ignored. so if you want to so see anything that makes sense, in cc convert scalar to colors.

also note, this old pcv (0.9) is compatible with blender 2.81, any newer (or older 2.80 in some cases), you will run into issues with everything. wrong color management, black renders, errors.. blender api is changing a lot and i keeping updated only latest pcv version on blendermarket.
